# Generated by Django 4.1.1 on 2023-12-12 10:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateEvaluationQuestionRemarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complexity_level', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationProcedureQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('complexity_level', models.IntegerField(default=1)),
                ('score', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoleProcedureAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_allow', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.proceduretypes')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roles.roles')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.proceduretypes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationProcedureRoleQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complexity_level', models.IntegerField(blank=True, null=True)),
                ('score', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluation_procedure_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.evaluationprocedurequestions')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roles.roles')),
            ],
        ),
        migrations.AddField(
            model_name='evaluationprocedurequestions',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.evaluations'),
        ),
        migrations.AddField(
            model_name='evaluationprocedurequestions',
            name='procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.proceduretypes'),
        ),
        migrations.AddField(
            model_name='evaluationprocedurequestions',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roles.roles'),
        ),
        migrations.AddField(
            model_name='evaluationprocedurequestions',
            name='role_procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluations.roleprocedureaccess'),
        ),
        migrations.CreateModel(
            name='CandidateEvaluations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_start', models.BooleanField(default=False)),
                ('start_date_time', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(blank=True, default=False, null=True)),
                ('total_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('total_marks_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('recommendation', models.CharField(blank=True, max_length=50, null=True)),
                ('evaluation_remarks', models.IntegerField(blank=True, choices=[(1, 'Hire'), (2, "Don't Hire"), (3, 'Discussion')], null=True)),
                ('is_rechecked', models.BooleanField(default=False)),
                ('is_mark_done', models.BooleanField(default=False)),
                ('is_cancel', models.BooleanField(default=False)),
                ('cancel_date_time', models.DateTimeField(blank=True, null=True)),
                ('reason_for_cancel', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancel_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_cancel_by', to=settings.AUTH_USER_MODEL)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.candidates')),
                ('candidate_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.candidatejobs')),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.evaluations')),
            ],
        ),
    ]
