# Generated by Django 4.1.1 on 2023-12-12 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stages', '0001_initial'),
        ('evaluations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateevaluations',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stages.stages'),
        ),
        migrations.AddField(
            model_name='candidateevaluationquestionremarks',
            name='candidate_evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.candidateevaluations'),
        ),
        migrations.AddField(
            model_name='candidateevaluationquestionremarks',
            name='evaluation_procedure_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.evaluationprocedurequestions'),
        ),
    ]
