# Generated by Django 4.1.1 on 2023-12-12 10:55

from django.db import migrations, models
import django.db.models.deletion
import helpers.image_uploads


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cost', models.PositiveIntegerField(default=0)),
                ('course_details', models.FileField(blank=True, null=True, upload_to=helpers.image_uploads.upload_course_skills_details)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='KavskillsEnrollmentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('full_name', models.CharField(max_length=250)),
                ('contact_number', models.CharField(max_length=200)),
                ('educational_qualifications', models.CharField(max_length=200)),
                ('university_name', models.CharField(max_length=200)),
                ('cnic_no', models.CharField(max_length=15)),
                ('major', models.CharField(max_length=150)),
                ('kav_skills_resume', models.FileField(upload_to=helpers.image_uploads.upload_kav_skills_resume)),
                ('cover_letter', models.FileField(blank=True, null=True, upload_to=helpers.image_uploads.upload_kav_skills_cover_letter)),
                ('joining_reason', models.TextField()),
                ('objectives', models.TextField()),
                ('financial_aid', models.BooleanField(default=False)),
                ('financial_aid_reason', models.TextField(blank=True, null=True)),
                ('additional_information', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('lnd_remark', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=30, null=True)),
                ('conversion_status', models.CharField(blank=True, choices=[('In progress', 'In progress'), ('Rejected', 'Rejected'), ('On hold', 'On hold'), ('Converted', 'Converted')], max_length=30, null=True)),
                ('skill_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kav_skills.skilltypes')),
            ],
        ),
    ]
