# Generated by Django 4.1.1 on 2023-12-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalallowance',
            name='year',
            field=models.IntegerField(default=2023),
        ),
    ]
