# Generated by Django 4.1.1 on 2023-12-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursements', '0002_medicalallowance_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='setleavesduration',
            name='year',
            field=models.IntegerField(default=2023),
        ),
    ]
