# Generated by Django 4.1.1 on 2023-12-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursements', '0003_setleavesduration_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalallowance',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='setleavesduration',
            name='year',
            field=models.IntegerField(),
        ),
    ]
