# Generated by Django 4.1.1 on 2024-01-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursements', '0004_alter_medicalallowance_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleavedates',
            name='status',
            field=models.CharField(blank=True, choices=[('approved', 'approved'), ('not-approved', 'not-approved')], max_length=100, null=True),
        ),
    ]
