# Generated by Django 4.1.1 on 2024-03-19 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('reimbursements', '0006_scriptstatuslogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesleaves',
            name='team_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emp_team_lead', to='employees.employees'),
        ),
        migrations.AddField(
            model_name='leavetypes',
            name='tl_required',
            field=models.BooleanField(default=False),
        ),
    ]
