# Generated by Django 4.1.1 on 2024-03-28 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employeeresume'),
        ('reimbursements', '0007_employeesleaves_team_lead_leavetypes_tl_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompensatoryLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('jira_ticket', models.CharField(blank=True, max_length=100, null=True)),
                ('team_lead_approval', models.CharField(choices=[('pending by team lead', 'Pending By Team Lead'), ('approved by team lead', 'Approved By Team Lead'), ('rejected by team lead', 'Rejected By Team Lead')], default='pending by team lead', max_length=30)),
                ('hr_approval', models.CharField(choices=[('pending by hr', 'Pending By HR'), ('approved by hr', 'Approved By HR'), ('rejected by hr', 'Rejected By HR')], default='pending by hr', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='employees.employees')),
                ('team_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensatory_team_lead', to='employees.employees')),
            ],
        ),
    ]
