# Generated by Django 4.1.1 on 2024-10-09 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_thirdpartytokens_organizationapikeys'),
        ('reimbursements', '0008_compensatoryleave'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptstatuslogs',
            name='staff_classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.staffclassification'),
        ),
    ]
