# Generated by Django 4.1.1 on 2025-01-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursements', '0010_employeeswfhrequest_employeeswfhrequestdates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetypes',
            name='gender_classification',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Both')], default=3),
        ),
    ]
