# Generated by Django 4.1.1 on 2025-02-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursements', '0011_leavetypes_gender_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleavecalculations',
            name='emp_yearly_leaves',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='employeeleavecalculations',
            name='remaining_leaves',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
