# Generated by Django 4.1.1 on 2024-08-30 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('positions', '0001_initial'),
        ('organizations', '0002_thirdpartytokens_organizationapikeys'),
        ('jobs', '0001_initial'),
        ('employees', '0002_employeeresume'),
        ('jd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplacementFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_start_date', models.DateField(blank=True, null=True)),
                ('no_of_individuals', models.IntegerField()),
                ('proposed_salary', models.IntegerField(blank=True, null=True)),
                ('requisition_date', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'Requested By Employee'), (2, 'Pending By HR'), (3, 'Initiated By HR'), (4, 'Request Approved'), (5, 'Request Rejected')], default=1)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('employee_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employeetypes')),
                ('jd_selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jd.jddescriptions')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.jobs')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='positions.positions')),
                ('replacement_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Requisition.replacementfor')),
                ('replacement_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replacement_of', to='employees.employees')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor', to='employees.employees')),
            ],
        ),
    ]
