# Generated by Django 4.1.1 on 2024-10-29 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Requisition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerequisition',
            name='replacement_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Requisition.replacementfor'),
        ),
    ]
