# Generated by Django 4.1.1 on 2024-07-30 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateassessmenttest',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_assessment_tests', to='candidates.candidates'),
        ),
        migrations.AddField(
            model_name='candidateassessmenttest',
            name='candidate_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_job_assessment_tests', to='candidates.candidatejobs'),
        ),
        migrations.AddField(
            model_name='candidateassessmentquestions',
            name='candidate_assessment_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.candidateassessmenttest'),
        ),
        migrations.AddField(
            model_name='candidateassessmentquestions',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.questions'),
        ),
        migrations.AddField(
            model_name='assessmenttests',
            name='assessment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.assessmenttypes'),
        ),
    ]
