# Generated by Django 4.1.1 on 2024-07-30 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0002_initial'),
        ('organizations', '0001_initial'),
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmenttests',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='assessmenttests',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='positions.positions'),
        ),
    ]
