# Generated by Django 4.1.1 on 2024-07-30 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmenttestfiles',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmenttestfiles',
            name='assessment_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.assessmenttests'),
        ),
        migrations.AddField(
            model_name='assessmenttestfiles',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentfilelogs',
            name='assessment_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.assessmenttestfiles'),
        ),
        migrations.AddField(
            model_name='assessmentfilelogs',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
