# Generated by Django 4.1.1 on 2024-10-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employeeresume'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='work_mode',
            field=models.CharField(choices=[('remote', 'Remote'), ('onsite', 'Onsite'), ('hybrid', 'Hybrid')], default='onsite', max_length=20),
        ),
    ]
