# Generated by Django 4.1.1 on 2024-10-31 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employeewfhallowance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeWFHAllowance',
        ),
    ]
