# Generated by Django 4.1.1 on 2023-12-12 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=12)),
                ('code_number', models.IntegerField(blank=True, null=True)),
                ('qualification', models.IntegerField(choices=[(1, "Bachelor's"), (2, "Master's"), (3, 'MPhil'), (4, 'other')])),
                ('years_of_experience', models.IntegerField(choices=[(1, '0-2 years'), (2, '2-4 years'), (3, '4-6 years'), (4, '6-8 years'), (5, '8-10 years'), (6, '10+ years')])),
                ('min_salary', models.IntegerField(blank=True, null=True)),
                ('max_salary', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.departments')),
                ('grouphead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.groupheads')),
                ('staff_classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.staffclassification')),
            ],
        ),
    ]
