# Generated by Django 4.1.1 on 2023-12-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseApplicants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_submitted', models.BooleanField(blank=True, default=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Unprocessed'), (2, 'In process'), (3, 'Approved'), (4, 'Rejected'), (5, 'Waitlisted')], default=1)),
                ('date', models.DateField(blank=True, null=True)),
                ('additional_comments', models.CharField(blank=True, max_length=250, null=True)),
                ('is_trainee', models.BooleanField(blank=True, default=False, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseApplicantsLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_status', models.IntegerField(blank=True, choices=[(1, 'Unprocessed'), (2, 'In process'), (3, 'Approved'), (4, 'Rejected'), (5, 'Waitlisted')], null=True)),
                ('decision_status', models.IntegerField(blank=True, choices=[(1, 'Approved'), (2, 'Rejected'), (3, 'Pending')], default=3, null=True)),
                ('decision_reason', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseSessionTraineeAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_status', models.IntegerField(blank=True, choices=[(1, 'Present'), (2, 'Absent'), (3, 'Leave')], null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseSessionTrainees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pass', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
