# Generated by Django 4.1.1 on 2023-12-12 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('applicants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesessiontrainees',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses'),
        ),
        migrations.AddField(
            model_name='coursesessiontrainees',
            name='course_applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicants.courseapplicants'),
        ),
    ]
