# Generated by Django 4.1.1 on 2023-12-12 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicants', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
        ('employees', '0001_initial'),
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesessiontrainees',
            name='course_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructors.coursesessions'),
        ),
        migrations.AddField(
            model_name='coursesessiontraineeattendance',
            name='course_session_trainee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicants.coursesessiontrainees'),
        ),
        migrations.AddField(
            model_name='coursesessiontraineeattendance',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructors.lectures'),
        ),
        migrations.AddField(
            model_name='coursesessiontraineeattendance',
            name='mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instructors.modeofinstructions'),
        ),
        migrations.AddField(
            model_name='courseapplicantslogs',
            name='course_applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_list', to='applicants.courseapplicants'),
        ),
        migrations.AddField(
            model_name='courseapplicantslogs',
            name='decision_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseapplicants',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses'),
        ),
        migrations.AddField(
            model_name='courseapplicants',
            name='course_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructors.coursesessions'),
        ),
        migrations.AddField(
            model_name='courseapplicants',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employees'),
        ),
    ]
