# Generated by Django 4.1.1 on 2024-02-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kav_apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='company',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
