# Generated by Django 4.1.1 on 2024-02-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kav_apis', '0002_contactform_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='company',
            field=models.CharField(max_length=200),
        ),
    ]
