# Generated by Django 4.1.1 on 2025-10-21 18:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0005_delete_employeewfhallowance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('rating', models.FloatField(default=0.0)),
                ('sentiment_label', models.CharField(blank=True, max_length=20, null=True)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('sentiment_raw', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_receiver', to='employees.employees')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_sender', to='employees.employees')),
            ],
        ),
    ]
