# Generated by Django 4.1.1 on 2025-10-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at'], 'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedback'},
        ),
        migrations.AddField(
            model_name='feedback',
            name='category',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('corrective', 'Corrective'), ('negative', 'Negative')], help_text='Feedback category derived from sentiment (positive/corrective/negative)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='impact_level',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], help_text='Impact or urgency level derived from feedback sentiment', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='improvement_areas',
            field=models.JSONField(blank=True, help_text='List of improvement points identified in the feedback', null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='strengths',
            field=models.JSONField(blank=True, help_text='List of positive aspects or skills identified in the feedback', null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='suggested_action',
            field=models.TextField(blank=True, help_text='Automatically generated suggestion for improvement or continuation', null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='tone',
            field=models.CharField(blank=True, help_text='Tone of the feedback, e.g. encouraging, formal, direct', max_length=50, null=True),
        ),
    ]
