# Generated by Django 4.1.1 on 2025-11-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_feedback_options_feedback_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='category',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('corrective', 'Corrective'), ('negative', 'Negative')], help_text='Feedback category derived from sentiment (positive/corrective/negative)', max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='WeeklyFeedbackSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField()),
                ('week_end_date', models.DateField()),
                ('total_feedbacks', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(default=0.0)),
                ('category_distribution', models.JSONField(default=dict)),
                ('sentiment_distribution', models.JSONField(default=dict)),
                ('daily_rating_trends', models.JSONField(default=list)),
                ('employee_id', models.IntegerField(blank=True, null=True)),
                ('employee_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Weekly Feedback Summaries',
                'ordering': ['-week_start_date'],
                'unique_together': {('week_start_date', 'week_end_date', 'employee_id')},
            },
        ),
    ]
