# Generated by Django 4.1.1 on 2025-11-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_feedback_category_weeklyfeedbacksummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='categories',
            field=models.JSONField(blank=True, help_text='Selected feedback categories/tags like Demo, Timelines, etc.', null=True),
        ),
    ]
