# Generated by Django 4.1.1 on 2025-11-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_feedback_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyfeedbacksummary',
            name='feedback_report',
            field=models.TextField(blank=True, help_text='Comprehensive feedback analysis report', null=True),
        ),
        migrations.AddField(
            model_name='weeklyfeedbacksummary',
            name='improvement_areas',
            field=models.JSONField(blank=True, default=list, help_text='List of improvement areas'),
        ),
        migrations.AddField(
            model_name='weeklyfeedbacksummary',
            name='strengths',
            field=models.JSONField(blank=True, default=list, help_text='List of identified strengths'),
        ),
    ]
