# Generated by Django 4.1.1 on 2025-11-17 13:34

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_weeklyfeedbacksummary_feedback_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyfeedbacksummary',
            name='category_distribution',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='weeklyfeedbacksummary',
            name='daily_rating_trends',
            field=models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='weeklyfeedbacksummary',
            name='feedback_report',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Comprehensive feedback analysis report as JSON'),
        ),
        migrations.AlterField(
            model_name='weeklyfeedbacksummary',
            name='improvement_areas',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='List of improvement areas'),
        ),
        migrations.AlterField(
            model_name='weeklyfeedbacksummary',
            name='sentiment_distribution',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='weeklyfeedbacksummary',
            name='strengths',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='List of identified strengths'),
        ),
    ]
