# Generated by Django 4.1.1 on 2025-11-18 10:59

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_alter_weeklyfeedbacksummary_category_distribution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='sentiment_spans',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Sentiment analysis spans for text highlighting', null=True),
        ),
    ]
