# Generated by Django 4.1.1 on 2025-11-19 10:47

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_feedback_sentiment_spans'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyFeedbackSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_start_date', models.DateField(help_text='First day of the month')),
                ('month_end_date', models.DateField(help_text='Last day of the month')),
                ('employee_id', models.IntegerField()),
                ('employee_name', models.CharField(max_length=255)),
                ('feedback_count', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(default=0.0)),
                ('previous_month_rating', models.FloatField(blank=True, null=True)),
                ('trend', models.CharField(choices=[('improving', 'Improving'), ('declining', 'Declining'), ('stable', 'Stable')], default='stable', max_length=20)),
                ('category_breakdown', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('sentiment_breakdown', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Monthly Feedback Summaries',
                'ordering': ['-month_start_date', 'employee_name'],
                'unique_together': {('month_start_date', 'employee_id')},
            },
        ),
    ]
