# Generated by Django 4.1.1 on 2025-11-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0008_monthlyfeedbacksummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='category',
            field=models.CharField(blank=True, choices=[('constructive', 'Constructive'), ('corrective', 'Corrective'), ('warning', 'Warning'), ('time_management', 'Time Management')], help_text='Feedback category derived from sentiment (positive/corrective/negative)', max_length=30, null=True),
        ),
    ]
