# Generated by Django 4.1.1 on 2025-12-02 10:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_delete_employeewfhallowance'),
        ('feedback', '0009_alter_feedback_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('task_leadership', 'Task Leadership in Critical Situations'), ('task_responsiveness', 'Task Responsiveness & Resolution'), ('technical_guidance', 'Technical Guidance'), ('team_communication', 'Team Communication and Collaboration'), ('organizational_skills', 'Organizational Skills'), ('work_standards', 'Adherence to Work Standards')], help_text='Main category from PMO Scoring Table', max_length=50)),
                ('action', models.CharField(help_text='Selected action/activity', max_length=50)),
                ('action_display', models.CharField(blank=True, help_text='Display name of the selected action', max_length=255)),
                ('merit_points', models.IntegerField(default=0, help_text='Automatically assigned merit points', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)])),
                ('demerit_points', models.IntegerField(default=0, help_text='Automatically assigned demerit points (stored as positive)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('evidence', models.TextField(blank=True, help_text='Evidence or reference (JIRA ticket, email, document, etc.)')),
                ('reference_link', models.URLField(blank=True, help_text='Optional link to evidence', max_length=500)),
                ('notes', models.TextField(blank=True, help_text='Additional comments or context')),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending Approval'), ('rejected', 'Rejected'), ('revoked', 'Revoked')], default='active', max_length=20)),
                ('date_occurred', models.DateField(default=django.utils.timezone.now, help_text='Date when the action occurred')),
                ('date_awarded', models.DateTimeField(auto_now_add=True, help_text='Date when score was recorded')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('awarded_by', models.ForeignKey(help_text='Employee who awarded the score', on_delete=django.db.models.deletion.CASCADE, related_name='scores_awarded', to='employees.employees')),
                ('employee', models.ForeignKey(help_text='Employee receiving the score', on_delete=django.db.models.deletion.CASCADE, related_name='scores_received', to='employees.employees')),
            ],
            options={
                'verbose_name': 'User Score',
                'verbose_name_plural': 'User Scores',
                'ordering': ['-date_awarded', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='userscore',
            index=models.Index(fields=['employee', 'category'], name='feedback_us_employe_f78982_idx'),
        ),
        migrations.AddIndex(
            model_name='userscore',
            index=models.Index(fields=['status', 'date_awarded'], name='feedback_us_status_26f86a_idx'),
        ),
    ]
