# Generated by Django 4.1.1 on 2025-12-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0010_userscore_userscore_feedback_us_employe_f78982_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscore',
            name='action',
            field=models.CharField(choices=[('leadership_critical_tasks', 'Taking ownership and completing critical tasks outside normal responsibilities'), ('leadership_failure', 'Failure to effectively manage additional responsibilities, causing delays'), ('response_individual', 'Prompt response to client inquiries regarding individual tasks outside of regular working hours'), ('resolution_individual', 'Timely resolution of any client concerns related to individual tasks during non-working hours'), ('response_team', 'Prompt response to client inquiries regarding team tasks outside of regular working hours'), ('resolution_team', 'Timely resolution of any client concerns related to team tasks during non-working hours'), ('mentorship_support', 'Providing mentorship or support to peers on complex tasks when needed, during non-working hours'), ('collaboration_failure', 'Failure to collaborate or assist team members as needed during non-working hours'), ('cross_department', 'Volunteering and completing tasks for cross-department collaborations during critical phases'), ('poor_collaboration', 'Poor collaboration impacting high-stakes outcomes'), ('positive_feedback', 'Positive client feedback on handling additional responsibilities'), ('negative_feedback', 'Negative client feedback on additional tasks or responsiveness'), ('proactive_prevention', 'Proactively preventing potential delays that would impact project criticality'), ('ineffective_management', 'Ineffective task management leading to team delays in high-criticality situations'), ('missing_work', 'Missing work without prior notice or reason'), ('repeated_delays', 'Repeated delays and bugs without a valid reason'), ('valuable_optimizations', 'Proposing valuable optimizations and leading implementation')], help_text='Selected action/activity', max_length=50),
        ),
    ]
