# Generated by Django 4.1.1 on 2025-12-04 08:24

from django.db import migrations, models
import feedback.models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0011_alter_userscore_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userscore',
            name='reference_link',
        ),
        migrations.AddField(
            model_name='userscore',
            name='reference_file',
            field=models.FileField(blank=True, help_text='Optional file upload for evidence (images, documents, etc.)', max_length=500, null=True, upload_to=feedback.models.user_score_file_path),
        ),
    ]
