# Generated by Django 4.1.1 on 2025-12-31 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('feedback', '0012_remove_userscore_reference_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Project for which feedback is given', null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projects'),
        ),
        migrations.AddField(
            model_name='userscore',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Project for which score is awarded (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projects'),
        ),
    ]
