# Generated by Django 4.1.1 on 2026-01-01 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0005_delete_employeewfhallowance'),
        ('feedback', '0013_feedback_project_userscore_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='receiver',
            field=models.ForeignKey(help_text='Employee receiving the feedback', on_delete=django.db.models.deletion.CASCADE, related_name='feedback_received', to='employees.employees'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='sender',
            field=models.ForeignKey(help_text='User sending the feedback', on_delete=django.db.models.deletion.CASCADE, related_name='feedback_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userscore',
            name='awarded_by',
            field=models.ForeignKey(help_text='User who awarded the score', on_delete=django.db.models.deletion.CASCADE, related_name='scores_awarded', to=settings.AUTH_USER_MODEL),
        ),
    ]
