# Generated by Django 4.1.1 on 2026-01-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0014_alter_feedback_receiver_alter_feedback_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='performance_categories',
            field=models.CharField(blank=True, choices=[('job_related_skills', 'Job-Related Skills'), ('productivity', 'Productivity'), ('quality_of_work', 'Quality of Work'), ('behaviour_with_superiors', 'Behaviour with Superiors'), ('interaction_with_colleagues', 'Interaction with Colleagues'), ('work_initiative_responsibility', 'Work Initiative & Responsibility'), ('capacity_to_learn_and_grow', 'Capacity to Learn and Grow'), ('stress_and_time_management', 'Stress and Time Management'), ('attendance_and_punctuality', 'Attendance and Punctuality'), ('compliance_with_company_policies', 'Compliance with Company Policies')], help_text='Performance evaluation categories', max_length=50, null=True),
        ),
    ]
