# Generated by Django 4.1.1 on 2024-10-14 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organizationmoduleaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmoduleaccess',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organizationmoduleaccess',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
    ]
