# Generated by Django 4.1.1 on 2024-01-31 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigations',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
