# Generated by Django 4.1.1 on 2023-12-12 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate_emails', '0001_initial'),
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateemails',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.candidates'),
        ),
        migrations.AddField(
            model_name='candidateemails',
            name='candidate_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidates.candidatejobs'),
        ),
    ]
