# Generated by Django 4.1.1 on 2023-12-12 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate_emails', '0002_initial'),
        ('email_templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateemails',
            name='email_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_templates.emailtemplates'),
        ),
    ]
