# Generated by Django 4.1.1 on 2023-12-12 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stages', '0001_initial'),
        ('candidate_emails', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateemails',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_stages_emails', to='stages.stages'),
        ),
        migrations.AddField(
            model_name='candidateemails',
            name='stage_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_stage_type_emails', to='stages.stagetypetemplates'),
        ),
        migrations.AddField(
            model_name='candidateemaillogs',
            name='action_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidateemaillogs',
            name='candidate_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate_emails.candidateemails'),
        ),
        migrations.AddField(
            model_name='candidateemailbody',
            name='candidate_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate_emails.candidateemails'),
        ),
        migrations.AddField(
            model_name='candidateemailattachments',
            name='candidate_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate_emails.candidateemails'),
        ),
    ]
