# Generated by Django 4.1.1 on 2024-09-04 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import helpers.image_uploads


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskify', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklogs',
            name='account_hour',
        ),
        migrations.RemoveField(
            model_name='tasklogs',
            name='actual_hours',
        ),
        migrations.RemoveField(
            model_name='tasklogs',
            name='external_ticket_reference',
        ),
        migrations.RemoveField(
            model_name='tasklogs',
            name='planned_hours',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='account_hour',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='actual_hours',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='external_ticket_reference',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='planned_hours',
        ),
        migrations.AddField(
            model_name='tasklogs',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_parent', to='taskify.tasks'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='is_child',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tasks',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taskify.tasks'),
        ),
        migrations.CreateModel(
            name='TaskAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(blank=True, null=True, upload_to=helpers.image_uploads.upload_tasks_attachments)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taskify.taskcomment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taskify.tasks')),
            ],
        ),
    ]
