# Generated by Django 4.1.1 on 2024-09-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskify', '0002_remove_tasklogs_account_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='account_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='actual_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='external_ticket_reference',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='planned_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
