# Generated by Django 4.1.1 on 2024-09-30 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskify', '0004_tasklogs_account_hour_tasklogs_actual_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTimeLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours_spent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('log_description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taskify.tasksstatus')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskify.tasks')),
            ],
        ),
    ]
