# Generated by Django 4.1.1 on 2024-09-30 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employeeresume'),
        ('taskify', '0005_tasktimelogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktimelogs',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employees'),
        ),
    ]
