# Generated by Django 4.1.1 on 2024-09-30 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskify', '0006_tasktimelogs_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasktimelogs',
            name='employee',
        ),
    ]
