# Generated by Django 4.1.1 on 2024-10-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskify', '0007_remove_tasktimelogs_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklogs',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
