# Generated by Django 4.1.1 on 2024-10-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskify', '0008_alter_tasklogs_description_alter_tasks_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklogs',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
