# Generated by Django 4.1.1 on 2024-11-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskify', '0010_tasktimelogs_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklogs',
            name='is_deactivated',
            field=models.BooleanField(default=''),
        ),
    ]
