# Generated by Django 4.1.1 on 2024-11-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskify', '0011_alter_tasklogs_is_deactivated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklogs',
            name='is_deactivated',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
