# Generated by Django 4.1.1 on 2024-11-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskify', '0012_alter_tasklogs_is_deactivated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklogs',
            old_name='time_log',
            new_name='hours_spent',
        ),
        migrations.AddField(
            model_name='tasklogs',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
