# Generated by Django 4.1.1 on 2024-11-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskify', '0013_rename_time_log_tasklogs_hours_spent_tasklogs_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklogs',
            name='hours_spent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
