# Generated by Django 4.1.1 on 2024-11-06 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskify', '0014_alter_tasklogs_hours_spent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklogs',
            name='hours_spent',
        ),
    ]
