# Generated by Django 4.1.1 on 2023-12-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_compositions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedsalary',
            name='compositions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
