# Generated by Django 4.1.1 on 2024-01-10 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_compositions', '0003_alter_processedsalary_gross_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedsalary',
            name='bank_account_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='processedsalary',
            name='bank_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='processedsalary',
            name='bank_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='processedsalary',
            name='non_taxable_amount_addons',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='processedsalary',
            name='non_taxable_amount_deductions',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='processedsalary',
            name='taxable_amount_addons',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='processedsalary',
            name='taxable_amount_deductions',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='processedsalary',
            name='transfer_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('transferred', 'Transferred')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='employeepayrollconfiguration',
            name='payroll_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll_compositions.payrollbatches'),
        ),
    ]
