# Generated by Django 4.1.1 on 2024-03-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_compositions', '0004_processedsalary_bank_account_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxslab',
            name='exemption_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
