# Generated by Django 4.1.1 on 2024-03-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_compositions', '0005_taxslab_exemption_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxslab',
            name='fixed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
