# Generated by Django 4.1.1 on 2023-12-12 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0002_initial'),
        ('time_intervals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatejobs',
            name='time_interval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_job_time_interval', to='time_intervals.timeintervals'),
        ),
    ]
