# Generated by Django 4.1.1 on 2024-08-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='is_already_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidates',
            name='reference_connection',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidates',
            name='reference_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
