# Generated by Django 4.1.1 on 2024-10-15 12:37

from django.db import migrations, models
import helpers.image_uploads


class Migration(migrations.Migration):

    dependencies = [
        ('datahive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='file',
            field=models.FileField(upload_to=helpers.image_uploads.upload_datahive_files),
        ),
        migrations.AlterField(
            model_name='documents',
            name='tags',
            field=models.ManyToManyField(blank=True, to='datahive.tags'),
        ),
    ]
