# Generated by Django 4.1.1 on 2024-10-15 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('datahive', '0002_alter_documents_file_alter_documents_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projects'),
        ),
    ]
