# Generated by Django 4.1.1 on 2023-12-12 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import helpers.image_uploads
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll_compositions', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LNDCertifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('mode_of_course', models.PositiveIntegerField(blank=True, choices=[(1, 'External'), (2, 'Online')], null=True)),
                ('relevance', models.PositiveIntegerField(blank=True, choices=[(1, 'Project'), (2, 'Personal Goal')], null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('certification_status', models.PositiveIntegerField(choices=[(1, 'Pending'), (2, 'Approved By Team Lead'), (3, 'Rejected By Team Lead'), (4, 'Approved By HR'), (5, 'Rejected By HR')], default=1)),
                ('course_url', models.URLField(blank=True, null=True)),
                ('course_reason', models.TextField(blank=True, null=True)),
                ('certificate', models.FileField(blank=True, null=True, upload_to=helpers.image_uploads.upload_certificate)),
                ('certification_receipt', models.FileField(blank=True, null=True, upload_to=helpers.image_uploads.upload_certificate_receipt)),
                ('feedback_comment', models.CharField(blank=True, max_length=250, null=True)),
                ('reimbursement_status', models.PositiveIntegerField(blank=True, choices=[(1, 'Reimbursement under process by Hr'), (2, 'Reimbursement approved by Hr'), (3, 'Reimbursement under process by Accountant'), (4, 'Reimbursement approved by Accountant')], null=True)),
                ('is_reimbursement', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_user', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employees')),
                ('processed_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll_compositions.salarybatch')),
                ('team_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_lead_user', to='employees.employees')),
            ],
        ),
        migrations.CreateModel(
            name='LNDCertificationLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_reason', models.TextField()),
                ('certification_status', models.PositiveIntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Approved By Team Lead'), (3, 'Rejected By Team Lead'), (4, 'Approved By HR'), (5, 'Rejected By HR')], null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certifyskills.lndcertifications')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
