# Generated by Django 4.1.1 on 2023-12-12 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import helpers.image_uploads


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applicants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseApplicantCustomEmails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('footer', models.TextField(blank=True, null=True)),
                ('is_trainee', models.BooleanField(default=False)),
                ('attachment', models.FileField(blank=True, null=True, upload_to=helpers.image_uploads.upload_course_applicant_attachments)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('course_applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicants.courseapplicants')),
            ],
        ),
    ]
