# Generated by Django 4.1.1 on 2023-12-12 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import helpers.image_uploads


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceMachineLogFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_file', models.FileField(upload_to=helpers.image_uploads.upload_organization_attendance_files)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeesAttendanceLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('attendance_status', models.CharField(blank=True, max_length=50, null=True)),
                ('comments', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employees')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeesAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('is_custom_time_set', models.BooleanField(blank=True, default=False, null=True)),
                ('is_check_in', models.BooleanField(default=False)),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('is_check_out', models.BooleanField(default=False)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('attendance_type', models.CharField(blank=True, choices=[('office', 'office'), ('WFH', 'WFH'), ('hybrid', 'hybrid'), ('H', 'H'), ('W', 'W'), ('A', 'A'), ('P', 'P'), ('L', 'L')], max_length=30, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance_machine_log_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees_attendance.attendancemachinelogfiles')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employees')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceMachines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_number', models.CharField(max_length=50)),
                ('machine_title', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
        ),
        migrations.AddField(
            model_name='attendancemachinelogfiles',
            name='attendance_machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees_attendance.attendancemachines'),
        ),
        migrations.AddField(
            model_name='attendancemachinelogfiles',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_process_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancemachinelogfiles',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
