# Generated by Django 4.1.1 on 2024-05-02 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employeeresume'),
        ('employees_attendance', '0002_employeesattendanceemaillogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceMachineslogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('mode', models.IntegerField(blank=True, choices=[(1, 'Finger'), (2, 'Face'), (3, 'Password'), (4, 'Card')], null=True)),
                ('state', models.IntegerField(blank=True, choices=[(0, 'check in'), (1, 'check out')], null=True)),
                ('status', models.CharField(blank=True, choices=[('added', 'added'), ('skipped', 'skipped')], max_length=30, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employees')),
            ],
        ),
    ]
