# Generated by Django 4.1.1 on 2024-05-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_attendance', '0003_attendancemachineslogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancemachineslogs',
            name='machine_serial_number',
            field=models.CharField(default='OPK6030056022200010', max_length=150),
        ),
    ]
