# Generated by Django 4.1.1 on 2024-08-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_attendance', '0004_attendancemachineslogs_machine_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancemachineslogs',
            name='machine_serial_number',
            field=models.CharField(max_length=150),
        ),
    ]
