# Generated by Django 4.1.1 on 2024-10-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_employeeworkexperience_is_currently_employed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeworkexperience',
            name='leaving_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
