# Generated by Django 4.1.1 on 2023-12-12 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('email_templates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageTypeTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('stage_type', models.IntegerField(choices=[(1, 'Dis-qualified'), (2, 'Job-Close'), (3, 'Job-Start')])),
                ('level', models.IntegerField(blank=True, default=1, null=True)),
                ('is_email', models.BooleanField(blank=True, default=True, null=True)),
                ('is_auto_sent_email', models.BooleanField(blank=True, default=False, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='email_templates.emailtemplates')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Stages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('level', models.IntegerField(blank=True, default=1, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_email', models.BooleanField(blank=True, default=True, null=True)),
                ('is_interview', models.BooleanField(blank=True, default=False, null=True)),
                ('is_evaluation', models.BooleanField(blank=True, default=False, null=True)),
                ('is_auto_sent_email', models.BooleanField(blank=True, default=False, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='email_templates.emailtemplates')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.proceduretypes')),
            ],
        ),
    ]
