# Generated by Django 4.1.1 on 2024-04-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stages',
            name='notify_to_admin',
            field=models.BooleanField(default=False),
        ),
    ]
