# Generated by Django 4.1.1 on 2023-12-12 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kpis', '0001_initial'),
        ('performance_configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeskpis',
            name='scale_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='performance_configuration.scalegroups'),
        ),
    ]
