# Generated by Django 4.1.1 on 2023-12-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epyearlysegmentation',
            name='status',
            field=models.CharField(choices=[('in-progress', 'in-progress'), ('completed', 'completed')], default='in-progress', max_length=60),
        ),
    ]
