# Generated by Django 4.1.1 on 2023-12-12 10:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateInterviewLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateInterviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('interview_date', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'To be set'), (2, 'Interview Set'), (3, 'Interview Start'), (4, 'Interview Completed'), (5, 'Cancel the Interview')], default=1)),
                ('start_date_time', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(blank=True, default=False, null=True)),
                ('complete_date_time', models.DateTimeField(blank=True, null=True)),
                ('is_cancel', models.BooleanField(blank=True, default=False, null=True)),
                ('reason_for_cancel', models.TextField(blank=True, null=True)),
                ('is_reschedule', models.BooleanField(default=False)),
                ('reschedule_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.candidates')),
                ('candidate_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.candidatejobs')),
                ('interview_mode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interviews.interviewmode')),
            ],
        ),
    ]
