# Generated by Django 4.1.1 on 2023-12-12 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interviews', '0001_initial'),
        ('stages', '0001_initial'),
        ('time_intervals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateinterviews',
            name='interview_time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='time_intervals.timeslots'),
        ),
        migrations.AddField(
            model_name='candidateinterviews',
            name='interviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidateinterviews',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stages.stages'),
        ),
        migrations.AddField(
            model_name='candidateinterviewlogs',
            name='candidate_interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interviews.candidateinterviews'),
        ),
        migrations.AddField(
            model_name='candidateinterviewlogs',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
