# Generated by Django 4.1.1 on 2024-08-30 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_thirdpartytokens_organizationapikeys'),
        ('interviews', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateinterviews',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateinterviews',
            name='interview_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='InterviewMedium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
        ),
        migrations.AddField(
            model_name='candidateinterviews',
            name='interview_medium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interviews.interviewmedium'),
        ),
    ]
