"""
Django settings for Universal_HRMS project.

Generated by 'django-admin startproject' using Django 4.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
import logging
from dotenv import load_dotenv 
load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = os.environ.get('DEFAULT_SECRET_KEY')
SECRET_KEY = 'django-insecure-ycns*bux5e!u@anm4v!o1j$s06-v&_b6^p33hv5i$8*=v0rcv*'


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'whitenoise.runserver_nostatic',
    'rest_framework_simplejwt',
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt.token_blacklist',
    'rest_framework.authtoken',
    'storages',
    'profiles_api',
    'logs',
    'organizations',
    'roles',
    'departments',
    'positions',
    'jd',
    'jobs',
    'stages',
    'scores',
    'candidates',
    'assessments',
    'skills',
    'banks',
    'companies',
    'institutes',
    'employees',
    'courses',
    'email_templates',
    'candidate_emails',
    'evaluations',
    'time_intervals',
    'interviews',
    'instructors',
    'applicants',
    'employees_attendance',
    'kind_notes',
    'projects',
    'payroll_compositions',
    'performance_evaluation',
    'performance_configuration',
    'navigations',
    'dashboards',
    'jira',
    'reimbursements',
    'course_applicant_emails',
    'certifyskills',
    'tickets',
    'training',
    'reports',
    'kpis',
    'kav_apis',
    'manuals',
    'kav_skills',
    'taskify',
    'meetings',
    'Requisition',
    'integrations',
    'datahive',
    'feedback',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Universal_HRMS.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Universal_HRMS.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
# DATABASES = {
#     'default': {
#         'ENGINE': os.environ.get('DATABASE_ENGINE'),
#         'NAME': os.environ.get('DATABASE_NAME'), 
#         'USER': os.environ.get('DATABASE_USER'), 
#         'PASSWORD': os.environ.get('DATABASE_PASSWORD'), 
#         'HOST': os.environ.get('DATABASE_HOST'),
#         'PORT': os.environ.get('DATABASE_PORT'),
#     }
# }



# DATABASES = {

#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'universal_hrms_live', 
#         'USER': 'doadmin', 
#         'PASSWORD': 'AVNS_5keKYEeTFgyynlu9uTc', 
#         'HOST': 'universal-hrms-do-user-14986681-0.c.db.ondigitalocean.com',
#         'PORT': '25060',
#     }

# }





# DATABASES = {

#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'hrms_db', 
#         'USER': 'postgres', 
#         'PASSWORD': 'saeed123', 
#         'HOST': 'localhost',
#         'PORT': '5432',
#     }

# }

DATABASES = {

    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'universal_hrms_dev_db', 
        'USER': 'doadmin', 
        'PASSWORD': 'AVNS_5keKYEeTFgyynlu9uTc', 
        'HOST': 'universal-hrms-do-user-14986681-0.c.db.ondigitalocean.com',
        'PORT': '25060',
    }

}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # 'DEFAULT_PARSER_CLASSES': (
    #     'rest_framework.parsers.JSONParser',
    #     'rest_framework.parsers.MultiPartParser'
    #     #...
    # )
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Karachi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

# STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#Added custom user model
AUTH_USER_MODEL = 'profiles_api.HrmsUsers'
 
# #For adding media 
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Email Configuration
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#EMAIL_HOST = 'smtp.gmail.com'
#EMAIL_USE_TLS = True
#EMAIL_PORT = 587
#EMAIL_HOST_USER = os.environ.get('EMAIL_USER')
#EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_PASS')


# Email Configuration ZOHO
EMAIL_BACKEND = 'django_smtp_ssl.SSLEmailBackend'
EMAIL_HOST = 'smtppro.zoho.com' #smtp.zoho.com
EMAIL_USE_SSL = True
EMAIL_PORT = 465
EMAIL_HOST_USER = 'noreply@kavmails.net'
EMAIL_HOST_PASSWORD = 'vdS&anu6'

# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'handlers': {
#         'file': {
#             'level': 'DEBUG',
#             'class': 'logging.FileHandler',
#             'filename': '../../debug.log',
#         },
#     },
#     'handlers': {
#         'file': {
#             'class': 'logging.handlers.FileHandler',
#             'filename': '../../file.log',
#             'level': 'DEBUG',
#         },
#     },
#     'loggers': {
#         'django': {
#             'handlers': ['file'],
#             'level': 'DEBUG',
#             'propagate': True,
#         },
#     },
# }

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'class': 'logging.FileHandler',
            'filename': '/tmp/file.log',
            'level': 'DEBUG',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}



#JWT TOKEN
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=200),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=10),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=300),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}


# Reset password valid for: 900 sec = 15 minutes  
PASSWORD_RESET_TIMEOUT = 900        

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://192.168.100.245:3000",
    "http://143.198.202.145:8000",
    "http://localhost:3001",
    "http://127.0.0.1:3000",
    "http://kav.smartpems.com",
    "http://192.168.18.226:3000",
    "http://hrms-react-kavtech.s3-website.ap-south-1.amazonaws.com",
    "http://hrms-react-kavtech-live.s3-website.ap-south-1.amazonaws.com",
    "http://192.168.1.173:3000",
    "http://178.128.85.114:30",
    "http://178.128.85.114",
    "https://kavtech.net",
    "https://kavtechsolutions.com",
    "https://universal-hrms-live.sgp1.cdn.digitaloceanspaces.com",
    "https://universal-hrms-live.sgp1.digitaloceanspaces.com",
]

# Storage backend settings Digital Ocean
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
AWS_ACCESS_KEY_ID = 'DO00RMBJ96L6G7RER2HW'
AWS_SECRET_ACCESS_KEY = 'QhyXmTyIk+4nNTMVTxf0abch1EpFV7PH9TvDGIAn5EE'
AWS_STORAGE_BUCKET_NAME = 'universal-hrms-live'
AWS_S3_REGION_NAME = 'sgp1'  # e.g., 'nyc3'
AWS_S3_ENDPOINT_URL = f'https://{AWS_S3_REGION_NAME}.digitaloceanspaces.com'

# Optional settings (depending on your requirements)
AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.sgp1.cdn.digitaloceanspaces.com'  # If using a custom domain
AWS_S3_FILE_OVERWRITE = False  # Set to True to overwrite existing files
AWS_DEFAULT_ACL = 'public-read'  # Use default bucket ACL settings
# # Static and media file URLs
STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/static/'
STATIC_ROOT = 'static'
MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/media/'
MEDIA_ROOT = ''



# Frontend URL for email links
FRONTEND_URL = 'http://localhost:3000'  # Change this to your production URL when deploying

# Or get from environment variable
# FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:3000')