# Generated by Django 4.1.1 on 2024-03-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspectsparameters',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
    ]
