# Generated by Django 4.1.1 on 2024-03-20 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_configuration', '0002_aspectsparameters_is_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='scalegroups',
            name='have_aspects',
            field=models.BooleanField(default=False),
        ),
    ]
