# Generated by Django 4.1.1 on 2024-06-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_configuration', '0003_scalegroups_have_aspects'),
    ]

    operations = [
        migrations.AddField(
            model_name='scalegroups',
            name='is_default_group',
            field=models.BooleanField(default=False),
        ),
    ]
