# Generated by Django 4.1.1 on 2024-03-28 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0002_employeeresume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('ticket_status', models.PositiveIntegerField(choices=[(1, 'Pending'), (2, 'In Progress by Team Lead'), (3, 'Rejected by Team Lead'), (4, 'Approved by Team Lead'), (5, 'In Progress by CTO'), (6, 'Rejected by CTO'), (7, 'Approved by CTO'), (8, 'In Progress by Admin'), (9, 'Rejected by Admin'), (10, 'Solved by Admin'), (11, 'In Progress by HR'), (12, 'Reject by HR'), (13, 'Solved by HR')], default=1)),
                ('category', models.PositiveIntegerField(blank=True, choices=[(1, 'Procurement'), (2, 'General'), (3, 'HR Services')], null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assign_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assign_to', to='employees.employees')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employees')),
                ('team_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_lead', to='employees.employees')),
                ('transfer_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_to', to='employees.employees')),
            ],
        ),
        migrations.CreateModel(
            name='TicketLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_reason', models.TextField(blank=True, null=True)),
                ('ticket_status', models.PositiveIntegerField(blank=True, choices=[(1, 'Pending'), (2, 'In Progress by Team Lead'), (3, 'Rejected by Team Lead'), (4, 'Approved by Team Lead'), (5, 'In Progress by CTO'), (6, 'Rejected by CTO'), (7, 'Approved by CTO'), (8, 'In Progress by Admin'), (9, 'Rejected by Admin'), (10, 'Solved by Admin'), (11, 'In Progress by HR'), (12, 'Reject by HR'), (13, 'Solved by HR')], null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decision_by', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket')),
            ],
        ),
    ]
