# Generated by Django 4.1.1 on 2024-07-02 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('employees', '0002_employeeresume'),
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('is_department', models.BooleanField(default=True)),
                ('is_main_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='TicketCategoryDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.departments')),
                ('ticket_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.ticketcategory')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='send_to_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.departments'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_status',
            field=models.PositiveIntegerField(choices=[(1, 'Pending'), (2, 'In Progress by Team Lead'), (3, 'Rejected by Team Lead'), (4, 'Approved by Team Lead'), (5, 'In Progress by CTO'), (6, 'Rejected by CTO'), (7, 'Approved by CTO'), (8, 'In Progress'), (9, 'Rejected'), (10, 'Solved'), (11, 'In Progress by Main Admin'), (12, 'Reject by Main Admin'), (13, 'Solved by Main Admin')], default=1),
        ),
        migrations.AlterField(
            model_name='ticketlogs',
            name='ticket_status',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Pending'), (2, 'In Progress by Team Lead'), (3, 'Rejected by Team Lead'), (4, 'Approved by Team Lead'), (5, 'In Progress by CTO'), (6, 'Rejected by CTO'), (7, 'Approved by CTO'), (8, 'In Progress'), (9, 'Rejected'), (10, 'Solved'), (11, 'In Progress by Main Admin'), (12, 'Reject by Main Admin'), (13, 'Solved by Main Admin')], null=True),
        ),
        migrations.CreateModel(
            name='TicketDepartmentEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employees')),
                ('ticket_category_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.ticketcategorydepartment')),
            ],
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_category', to='tickets.ticketcategory'),
        ),
    ]
